package com.eldrix.openconsent.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.AuthorityLogic;
import com.eldrix.openconsent.model.Project;

/**
 * Class _Authority was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Authority extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<AuthorityLogic> LOGIC = Property.create("logic", AuthorityLogic.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> UUID = Property.create("uuid", String.class);
    public static final Property<List<Project>> PROJECTS = Property.create("projects", List.class);

    public void setLogic(AuthorityLogic logic) {
        writeProperty("logic", logic);
    }
    public AuthorityLogic getLogic() {
        return (AuthorityLogic)readProperty("logic");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }

    public void addToProjects(Project obj) {
        addToManyTarget("projects", obj, true);
    }
    public void removeFromProjects(Project obj) {
        removeToManyTarget("projects", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Project> getProjects() {
        return (List<Project>)readProperty("projects");
    }


    protected abstract void onPostAdd();

    protected abstract void onPostLoad();

}
