package com.eldrix.openconsent.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.AuthorityLogic;

/**
 * Class _Authority was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Authority extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<AuthorityLogic> LOGIC = new Property<AuthorityLogic>("logic");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> UUID = new Property<String>("uuid");

    public void setLogic(AuthorityLogic logic) {
        writeProperty("logic", logic);
    }
    public AuthorityLogic getLogic() {
        return (AuthorityLogic)readProperty("logic");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }

    protected abstract void onPostAdd();

    protected abstract void onPostLoad();

}
