package com.eldrix.openconsent.model.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.ConsentFormStatus;
import com.eldrix.openconsent.model.ConsentItem;
import com.eldrix.openconsent.model.Project;

/**
 * Class _ConsentForm was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ConsentForm extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> CREATED_DATE_TIME = Property.create("createdDateTime", LocalDateTime.class);
    public static final Property<LocalDateTime> FINAL_DATE_TIME = Property.create("finalDateTime", LocalDateTime.class);
    public static final Property<String> INFORMATION = Property.create("information", String.class);
    public static final Property<ConsentFormStatus> STATUS = Property.create("status", ConsentFormStatus.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<String> VERSION_STRING = Property.create("versionString", String.class);
    public static final Property<List<ConsentItem>> CONSENT_ITEMS = Property.create("consentItems", List.class);
    public static final Property<Project> PROJECT = Property.create("project", Project.class);

    public void setCreatedDateTime(LocalDateTime createdDateTime) {
        writeProperty("createdDateTime", createdDateTime);
    }
    public LocalDateTime getCreatedDateTime() {
        return (LocalDateTime)readProperty("createdDateTime");
    }

    public void setFinalDateTime(LocalDateTime finalDateTime) {
        writeProperty("finalDateTime", finalDateTime);
    }
    public LocalDateTime getFinalDateTime() {
        return (LocalDateTime)readProperty("finalDateTime");
    }

    public void setInformation(String information) {
        writeProperty("information", information);
    }
    public String getInformation() {
        return (String)readProperty("information");
    }

    public void setStatus(ConsentFormStatus status) {
        writeProperty("status", status);
    }
    public ConsentFormStatus getStatus() {
        return (ConsentFormStatus)readProperty("status");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setVersionString(String versionString) {
        writeProperty("versionString", versionString);
    }
    public String getVersionString() {
        return (String)readProperty("versionString");
    }

    public void addToConsentItems(ConsentItem obj) {
        addToManyTarget("consentItems", obj, true);
    }
    public void removeFromConsentItems(ConsentItem obj) {
        removeToManyTarget("consentItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ConsentItem> getConsentItems() {
        return (List<ConsentItem>)readProperty("consentItems");
    }


    public void setProject(Project project) {
        setToOneTarget("project", project, true);
    }

    public Project getProject() {
        return (Project)readProperty("project");
    }


    protected abstract void onPostAdd();

}
