package com.eldrix.openconsent.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.Authority;
import com.eldrix.openconsent.model.Patient;

/**
 * Class _Endorsement was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Endorsement extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ENCRYPTED_AUTHORITY_PSEUDONYM = Property.create("encryptedAuthorityPseudonym", String.class);
    public static final Property<Authority> AUTHORITY = Property.create("authority", Authority.class);
    public static final Property<Patient> PATIENT = Property.create("patient", Patient.class);

    public void setEncryptedAuthorityPseudonym(String encryptedAuthorityPseudonym) {
        writeProperty("encryptedAuthorityPseudonym", encryptedAuthorityPseudonym);
    }
    public String getEncryptedAuthorityPseudonym() {
        return (String)readProperty("encryptedAuthorityPseudonym");
    }

    public void setAuthority(Authority authority) {
        setToOneTarget("authority", authority, true);
    }

    public Authority getAuthority() {
        return (Authority)readProperty("authority");
    }


    public void setPatient(Patient patient) {
        setToOneTarget("patient", patient, true);
    }

    public Patient getPatient() {
        return (Patient)readProperty("patient");
    }


}
