package com.eldrix.openconsent.model.auto;

import java.time.LocalDate;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.Project;

/**
 * Class _Episode was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Episode extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDate> DATE_REGISTRATION = new Property<LocalDate>("dateRegistration");
    public static final Property<String> PATIENT_IDENTIFIER = new Property<String>("patientIdentifier");
    public static final Property<Project> PROJECT = new Property<Project>("project");

    public void setDateRegistration(LocalDate dateRegistration) {
        writeProperty("dateRegistration", dateRegistration);
    }
    public LocalDate getDateRegistration() {
        return (LocalDate)readProperty("dateRegistration");
    }

    public void setPatientIdentifier(String patientIdentifier) {
        writeProperty("patientIdentifier", patientIdentifier);
    }
    public String getPatientIdentifier() {
        return (String)readProperty("patientIdentifier");
    }

    public void setProject(Project project) {
        setToOneTarget("project", project, true);
    }

    public Project getProject() {
        return (Project)readProperty("project");
    }


}
