package com.eldrix.openconsent.model.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.ConsentForm;
import com.eldrix.openconsent.model.Episode;
import com.eldrix.openconsent.model.PermissionItem;

/**
 * Class _PermissionForm was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PermissionForm extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> DATE_TIME_CREATED = Property.create("dateTimeCreated", LocalDateTime.class);
    public static final Property<Integer> EPISODE_FK = Property.create("episodeFk", Integer.class);
    public static final Property<ConsentForm> CONSENT_FORM = Property.create("consentForm", ConsentForm.class);
    public static final Property<Episode> EPISODE = Property.create("episode", Episode.class);
    public static final Property<List<PermissionItem>> PERMISSION_ITEMS = Property.create("permissionItems", List.class);

    public void setDateTimeCreated(LocalDateTime dateTimeCreated) {
        writeProperty("dateTimeCreated", dateTimeCreated);
    }
    public LocalDateTime getDateTimeCreated() {
        return (LocalDateTime)readProperty("dateTimeCreated");
    }

    public void setEpisodeFk(int episodeFk) {
        writeProperty("episodeFk", episodeFk);
    }
    public int getEpisodeFk() {
        Object value = readProperty("episodeFk");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConsentForm(ConsentForm consentForm) {
        setToOneTarget("consentForm", consentForm, true);
    }

    public ConsentForm getConsentForm() {
        return (ConsentForm)readProperty("consentForm");
    }


    public void setEpisode(Episode episode) {
        setToOneTarget("episode", episode, true);
    }

    public Episode getEpisode() {
        return (Episode)readProperty("episode");
    }


    public void addToPermissionItems(PermissionItem obj) {
        addToManyTarget("permissionItems", obj, true);
    }
    public void removeFromPermissionItems(PermissionItem obj) {
        removeToManyTarget("permissionItems", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PermissionItem> getPermissionItems() {
        return (List<PermissionItem>)readProperty("permissionItems");
    }


    protected abstract void onPostAdd();

}
