package com.eldrix.openconsent.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.ConsentItem;
import com.eldrix.openconsent.model.PermissionForm;
import com.eldrix.openconsent.model.PermissionResponse;

/**
 * Class _PermissionItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PermissionItem extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<PermissionResponse> RESPONSE = Property.create("response", PermissionResponse.class);
    public static final Property<ConsentItem> CONSENT_ITEM = Property.create("consentItem", ConsentItem.class);
    public static final Property<PermissionForm> PERMISSION_FORM = Property.create("permissionForm", PermissionForm.class);

    public void setResponse(PermissionResponse response) {
        writeProperty("response", response);
    }
    public PermissionResponse getResponse() {
        return (PermissionResponse)readProperty("response");
    }

    public void setConsentItem(ConsentItem consentItem) {
        setToOneTarget("consentItem", consentItem, true);
    }

    public ConsentItem getConsentItem() {
        return (ConsentItem)readProperty("consentItem");
    }


    public void setPermissionForm(PermissionForm permissionForm) {
        setToOneTarget("permissionForm", permissionForm, true);
    }

    public PermissionForm getPermissionForm() {
        return (PermissionForm)readProperty("permissionForm");
    }


}
