package com.eldrix.openconsent.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.Authority;

/**
 * Class _Project was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Project extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCRIPTION = new Property<String>("description");
    public static final Property<String> TITLE = new Property<String>("title");
    public static final Property<String> UUID = new Property<String>("uuid");
    public static final Property<Authority> AUTHORITY = new Property<Authority>("authority");

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }

    public void setAuthority(Authority authority) {
        setToOneTarget("authority", authority, true);
    }

    public Authority getAuthority() {
        return (Authority)readProperty("authority");
    }


    protected abstract void onPostAdd();

    protected abstract void onPostLoad();

}
