package com.eldrix.openconsent.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.Patient;

/**
 * Class _Registration was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Registration extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ENCRYPTED_PSEUDONYM = Property.create("encryptedPseudonym", String.class);
    public static final Property<Patient> PATIENT = Property.create("patient", Patient.class);

    public void setEncryptedPseudonym(String encryptedPseudonym) {
        writeProperty("encryptedPseudonym", encryptedPseudonym);
    }
    public String getEncryptedPseudonym() {
        return (String)readProperty("encryptedPseudonym");
    }

    public void setPatient(Patient patient) {
        setToOneTarget("patient", patient, true);
    }

    public Patient getPatient() {
        return (Patient)readProperty("patient");
    }


}
