package com.eldrix.openconsent.model.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.eldrix.openconsent.model.Patient;

/**
 * Class _Registration was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Registration extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PATIENT_FK_PK_COLUMN = "patient_fk";

    public static final Property<String> ENCRYPTED_IDENTIFIER = new Property<String>("encryptedIdentifier");
    public static final Property<Patient> PATIENT = new Property<Patient>("patient");

    public void setEncryptedIdentifier(String encryptedIdentifier) {
        writeProperty("encryptedIdentifier", encryptedIdentifier);
    }
    public String getEncryptedIdentifier() {
        return (String)readProperty("encryptedIdentifier");
    }

    public void setPatient(Patient patient) {
        setToOneTarget("patient", patient, true);
    }

    public Patient getPatient() {
        return (Patient)readProperty("patient");
    }


}
